"""create_audit_logs

Revision ID: 5540a2390864
Revises: 0006_rehash_seeded_passwords
Create Date: 2026-07-12 14:50:22.435283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5540a2390864'
down_revision: Union[str, None] = '0006_rehash_seeded_passwords'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.drop_index(op.f('uq_drivers_license_number'), table_name='drivers')
    op.create_index(op.f('ix_drivers_license_number'), 'drivers', ['license_number'], unique=True)
    op.drop_constraint(op.f('drivers_created_by_fkey'), 'drivers', type_='foreignkey')
    op.drop_constraint(op.f('drivers_updated_by_fkey'), 'drivers', type_='foreignkey')
    op.create_foreign_key(None, 'drivers', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'drivers', 'users', ['created_by'], ['id'])
    op.drop_index(op.f('uq_roles_name'), table_name='roles')
    op.create_unique_constraint(None, 'roles', ['name'])
    op.drop_index(op.f('uq_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('uq_vehicles_registration_number'), table_name='vehicles')
    op.create_index(op.f('ix_vehicles_registration_number'), 'vehicles', ['registration_number'], unique=True)
    op.drop_constraint(op.f('vehicles_created_by_fkey'), 'vehicles', type_='foreignkey')
    op.drop_constraint(op.f('vehicles_updated_by_fkey'), 'vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicles', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'vehicles', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('vehicles_updated_by_fkey'), 'vehicles', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('vehicles_created_by_fkey'), 'vehicles', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_vehicles_registration_number'), table_name='vehicles')
    op.create_index(op.f('uq_vehicles_registration_number'), 'vehicles', ['registration_number'], unique=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('uq_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint(None, 'roles', type_='unique')
    op.create_index(op.f('uq_roles_name'), 'roles', ['name'], unique=True)
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.create_foreign_key(op.f('drivers_updated_by_fkey'), 'drivers', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('drivers_created_by_fkey'), 'drivers', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_drivers_license_number'), table_name='drivers')
    op.create_index(op.f('uq_drivers_license_number'), 'drivers', ['license_number'], unique=True)
    op.drop_index('idx_audit_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
